version: "3.1"

services:
    influxdb:
        image: influxdb:2.7.1
        container_name: influxdb
        volumes:
            - type: volume
              source: influxdb-data
              target: /var/lib/influxdb
        environment:
            INFLUXDB_META_DIR: /var/lib/influxdb/meta
            INFLUXDB_DATA_DIR: /var/lib/influxdb/data
            INFLUXDB_DATA_WAL_DIR: /var/lib/influxdb/data
            INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
            INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
            INFLUXDB_DATA_SERIES_ID_SET_CACHE_SIZE: 100
            # INFLUXDB_HTTP_BIND_ADDRESS: :${INFLUXDB_PORT}
            # INFLUXDB_HTTP_ENABLED: "true"
            # INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_INIT_MODE: setup
            INFLUXDB_INIT_USERNAME: admin
            INFLUXDB_INIT_PASSWORD: lostman@123
            INFLUXDB_INIT_ORG: Experiom
            INFLUXDB_INIT_BUCKET: stocks
            INFLUXDB_DB: stocks_master
        ports:
            - 8086:8086
        restart: unless-stopped
        networks:
            - stocks

    grafana:
        container_name: grafana
        image: grafana/grafana:10.1.1
        volumes:
            - type: volume
              source: grafana-data
              target: /var/lib/grafana
        ports:
            - 3001:3000
        environment:
            GF_PATHS_DATA: /var/lib/grafana
            GF_PATHS_PLUGINS: /var/lib/grafana/plugins
            GF_PATHS_PROVISIONING: /etc/grafana/provisioning
            
            # GF_SERVER_HTTP_PORT: 3000
            # GF_SERVER_METRICS_DOMAIN: ${METRICS_DOMAIN}
            # GF_SERVER_ROOT_URL: https://${METRICS_DOMAIN}

            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: lostman@123

            GF_LOG_MODE: console

            # Variables for setting up the InfluxDB data source
            #INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USER}
            #INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
            #INFLUXDB_INIT_ORG: experiom
            #INFLUXDB_INIT_BUCKET: stocks
        networks:
            - stocks
        restart: unless-stopped
        depends_on:
            - influxdb
networks:
    stocks:
        driver: bridge
volumes:
    influxdb-data:
        external: true

    grafana-data:
        external: true
